### ISSUE TITLE
Feature Request: Power: Korrekturfaktor

### ISSUE THREAD

**Issue by steff393** [steff393/wbec#102]
Den aus der Wallbox ausgelesen Wert für die Leistung mit einem Korrekturfaktor beaufschlagen, s. [hier](https://openwb.de/forum/viewtopic.php?p=93461#p93461) und #97 
Wichtig jedoch: Dies würde nur für die Leistung "power" gelten und die Stromzähler energyI, energyP und energyC **nicht** beeinflussen.
-> zu klären, ob das zu unerwünschten Effekten führen kann

**Comment by steff393** [comment]
Workaround für EVCC:
```
meters:
- name: wbec-LP1-Meter
  type: custom
  power:
    source: mqtt
    topic: wbec/lp/1/power
    scale: 0.919               <--------------
  energy:
    source: mqtt
    topic: wbec/lp/1/energy
    scale: 0.919               <--------------
  currents:
    - source: mqtt
      topic: wbec/lp/1/currL1
    - source: mqtt
      topic: wbec/lp/1/currL2
    - source: mqtt
      topic: wbec/lp/1/currL3
```

Danke an Norbert!
