### ISSUE TITLE
Ladestrom Einstellung vs. Realität

### ISSUE THREAD

**Issue by marc107** [steff393/wbec#97]
Hallo zusammen,

zunächst einmal vielen Dank @steff393 für die Übersendung in 2022 und die tolle Arbeit im Projekt. ;-)

Nach einigen Startproblemen mit der Verbindung zur Heidelberg konnte ich nunmehr eine erfolgreiche Verbindung aufbauen.
Wbec läuft in nachfolgender Config:

```
{"wbec":{"version":"v0.4.9",
"bldDate":"May 28 2023 18:43:20",
"timeNow":"17:49:16"},
"box":[{"busId":1,
"version":"108",
"chgStat":7,
"currL1":32,
"currL2":31,
"currL3":32,
"pcbTemp":299,
"voltL1":238,
"voltL2":237,
"voltL3":236,
"extLock":1,
"power":2315,
"energyP":1.087,
"energyI":586.821,
"energyC":1.087,
"currMax":16,
"currMin":6,
"logStr":"00.779.2909/02 025013 2150 HD_EnergyControl",
"wdTmOut":60000,
"standby":4,
"remLock":1,
"currLim":160,
"currFs":0,
"lmReq":160,
"lmLim":255,
"resCode":"0"}],
"modbus":{"state":{"lastTm":2768867,"millis":2771081}},
"rfid":{"enabled":false,
"release":false,
"lastId":""},
"pv":{"mode":0,
"watt":0},
"wifi":{"mac":"44:17:93:0E:xx:53",
"rssi":-78,
"signal":44,
"channel":6}}
```

Stelle ich nunmehr den Ladestrom in wbec auf 6A, so wird laut MQTT von wbec nacfolgendes ausgegeben:
```
power = 1394
currL1 = 1.9
currL2 = 1.9
currL3 = 1.9
```
Erhöhe ich in wbec den Ladestrom auf 16A, so ergibt sich folgende Ausgabe via MQTT:
```
power = 2316
currL1 = 3.3
currL2 = 3.1
currL3 = 13.2
```

Ich stelle mir die Frage, warum der Strom nicht auf 16 A erhöht wird. Der Akku des Fiat 500e hatte zum Zeitpunkt des Ladens ca. 45%.

Inwiefern es relevant ist vermag ich nicht zu beurteilen, aber ich gebe die Werte via MQTT an evcc weiter.
Die evcc.yaml ist wie folgt definiert:
```
# mqtt message broker
mqtt:
  broker: 192.168.178.xx:1883
  # topic: evcc # root topic for publishing, set empty to disable
  # user:
  # password:

#interval: 60s

meters:
- type: custom
  name: Stromzaehler
  power:
    source: mqtt
    topic: fhem/Strom
    timeout: 30s
    scale: 1
- name: wbec-LP1-Meter
  type: custom
  power:
    source: mqtt
    topic: wbec/lp/1/power
  energy:
    source: mqtt
    topic: wbec/lp/1/energy
  currents:
    - source: mqtt
      topic: wbec/lp/1/currL1
    - source: mqtt
      topic: wbec/lp/1/currL2
    - source: mqtt
      topic: wbec/lp/1/currL3

- type: custom
  name: PV_gesamt
  power:
    source: mqtt
    topic: fhem/PV_gesamt
    timeout: 30s
    scale: 1

chargers:
- name: wbec-LP1
  type: custom
  status:
    source: mqtt
    topic: wbec/lp/1/status
  enabled:
    source: mqtt
    topic: wbec/lp/1/enabled
  enable:
    source: mqtt
    topic: wbec/lp/1/enable
  maxcurrent:
    source: mqtt
    topic: wbec/lp/1/maxcurrent

site:
  title: Heidelberg
  meters:
    grid: Stromzaehler
    pv: PV_gesamt

loadpoints:
- title: Out # display name for UI
  charger: wbec-LP1 # Wallbox Referenz
  phases: 1
  mincurrent: 6
  maxcurrent: 16
  resetOnDisconnect: true 
  mode: now
```

In evcc werden wiederum völlig andere und falsche Werte angegeben:

![image](https://github.com/steff393/wbec/assets/63843545/1211367b-cce8-4a01-9ae6-c984ee481eb1)

Die Leistung in evcc ändert sich nicht, egal ob im wbec 6A oder 16A eingestellt sind.

Hat jemand einen Erklärungsansatz dafür?

Viele Grüße

Marc

**Comment by steff393** [comment]
Hallo Marc,
die Wallbox legt nur den maximal erlaubten Ladestrom fest. Das Auto entscheidet anschließend, wie viel Strom es wirklich zieht.

Es gibt zum einen die Leistungsmessung in der Wallbox ("power"). Andererseits kann evcc die Leistung auch aus Strom und Spannung berechnen. Diese Werte können schon voneinander abweichen (v.a. da evcc die realen Spannungen ja gar nicht sieht, s.o., und vermutlich einen Ersatzwert annimmt). Welcher Wert jetzt aber näher an der Realität ist weiß ich leider nicht.

**Comment by marc107** [comment]
Danke für deine schnelle Rückmeldung!

> die Wallbox legt nur den maximal erlaubten Ladestrom fest. Das Auto entscheidet anschließend, wie viel Strom es wirklich zieht.
Ich muss nachher mal im Auto nachsehen. Nicht, dass dort eine Begrenzung von einer Mitfahrerin eingestellt wurde... ;-)

Die Frage der Abweichungen erscheint mir wohl besser im evcc-Forum untergebracht. Konntest du diese auch beobachten?

**Comment by marc107** [comment]
Das liest sich ähnlich:
https://github.com/evcc-io/evcc/discussions/5928

**Comment by JTL42** [comment]
Hallo Marc,

der Fiat 500e hat 5 Ladestufen, die in ca. 20% Schritten die Ladeleistung festlegen. Bei Stufe 3 beträgt diese also 60%. Du kannst WBEC so konfigurieren, dass er das kompensiert, indem Du in cfgPvPhFactor einen Wert von 44 anstelle 69 einträgst. Bei anderen Ladestufen entsprechend mehr oder weniger. Das ganze hat sogar einen entscheidenden Vorteil. Du brauchst normalerweise 6A um das Laden zu starten, d.h. beim PV Laden würde es etwa mindestens 4,2KW benötigen. Bei Ladestufe 3 kannst Du aber bereits bei 2,4KW laden, weil der Fiat nicht die gesamte Leistung zieht. 

Schau also mal auf die eingestellte Ladeleistung und melde Dich bei weiteren Fragen. Habe ebenfalls einen 500e 😊

Grüße 
JT

**Comment by marc107** [comment]
Hi JT,

vielen Dank für die Tipps!
Ich konnte mich am WE ein wenig mit dem Thema auseinandersetzen und musste dabei feststellen, dass im Auto Ladestufe 1 eingestellt ist. In meinem Fall lädt der Fiat dann mit 3x1,9A == 1,4kW. Das finde ich super, da ich nur eine sehr kleine PV-Anlage mit 2kWp besitze und das Auto nur sehr wenig (ca. 3500km/a) bewegt wird.

Ein wenig schade finde ich, dass in evcc der falsche Wert für die Ladeleistung angezeigt wird, da ich noch nicht genau weiß, welchen Einfuss das Ganze auf das Überschussladen nimmt.

Den Ladepunkt habe ich in evcc wie folgt definiert:

```
loadpoints:
- title: Out # display name for UI
  charger: wbec-LP1 # Wallbox Referenz
  phases: 1
  mincurrent: 6
  maxcurrent: 16
  resetOnDisconnect: true 
  mode: pv
  enable:
    threshold: -750 # evcc startet das Laden, wenn 2 Minuten lang mindestens 750 W Einspeiseleistung (Überschuss) vorhanden sind
    delay: 5m
  disable:
    threshold: 750 # evcc beendet das Laden, wenn 15 Minuten lang mehr als 750 W Netzstrom bezogen wurde
    delay: 15m # Ausschalteverzögerung, Laufzeit dabei mindestens 15 Minuten
```

Ich befürchte, dass die von evcc angenommene Ladeleistung von 3,7kWh nunmehr dazu führt, dass er das Überschussladen unterbricht, da er ggf. denkt, dass er mehr als 750W aus dem Netz bezieht. Wobei der Screenshot dargestellte Wert für den Netzbezug i.H.v. 2,5kW ja stimmt, nur die Ladeleistung halt nicht.
Da es die nächsten Tage schönes Wetter geben wird, sollte das ja herauszubekommen sein.
Wobei mich der optische Mangel irgendwie nervt... ;-)
